### ISSUE TITLE
App crash when i open multiple chips detail and closed one by one

### ISSUE THREAD

**Issue by CHRehan** [pchmn/MaterialChipsInput#104]
```
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: shahisawari.pk, PID: 6989
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:411)
        at com.pchmn.materialchips.adapter.ChipsAdapter.removeChip(ChipsAdapter.java:305)
        at com.pchmn.materialchips.adapter.ChipsAdapter$5$1.onClick(ChipsAdapter.java:228)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by midhun-murali** [comment]
this occurs for me also, is there any solution? @CHRehan @marconi1992 @pchmn

**Comment by techwizard1** [comment]
Remove it by Object ID or Chip Label
