### ISSUE TITLE
Resources$NotFoundException: Error.

### ISSUE THREAD

**Issue by Shahxad-Akram** [pchmn/MaterialChipsInput#109]
Hi when i try to remove or click a chip in chipInput , i get this error

```
    android.content.res.Resources$NotFoundException: Resource ID #0x7f060030 type #0x2 is not valid
        at android.content.res.Resources.getColor(Resources.java:2176)
        at android.content.Context.getColor(Context.java:447)
        at android.support.v4.content.ContextCompatApi23.getColor(ContextCompatApi23.java:32)
        at android.support.v4.content.ContextCompat.getColor(ContextCompat.java:432)
        at com.pchmn.materialchips.views.DetailedChipView.getBackgroundColor(DetailedChipView.java:154)
        at com.pchmn.materialchips.views.DetailedChipView.newInstance(DetailedChipView.java:256)
        at com.pchmn.materialchips.views.DetailedChipView.access$000(DetailedChipView.java:35)
        at com.pchmn.materialchips.views.DetailedChipView$Builder.build(DetailedChipView.java:235)
        at com.pchmn.materialchips.ChipsInput.getDetailedChipView(ChipsInput.java:230)
        at com.pchmn.materialchips.adapter.ChipsAdapter$5.onClick(ChipsAdapter.java:221)
        at android.view.View.performClick(View.java:5697)
        at android.view.View$PerformClick.run(View.java:22526)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7225)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by mwshubham** [comment]
add `app:chip_detailed_backgroundColor`
