### ISSUE TITLE
int android.view.ViewGroup$MarginLayoutParams.topMargin' on a null object reference

### ISSUE THREAD

**Issue by wifirevaithi** [pchmn/MaterialChipsInput#112]
java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$MarginLayoutParams.topMargin' on a null object reference
        at com.pchmn.materialchips.views.FilterableListView.fadeIn(FilterableListView.java:135)
        at com.pchmn.materialchips.views.FilterableListView$2.onFilterComplete(FilterableListView.java:113)
        at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:285)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)

**Comment by teer-hossain** [comment]
I had the same issue, and changing the height of the view to 'wrap_content' fixed it
.

**Comment by IgorHorta** [comment]
Any updates on this ?
