### ISSUE TITLE
NullPointerException in new version

### ISSUE THREAD

**Issue by duke1712** [pchmn/MaterialChipsInput#3]
I upgraded to the new version and then I got the below error.

` java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                               at com.pchmn.materialchips.util.LetterTileProvider.getLetterTile(LetterTileProvider.java:83)
                                                                               at com.pchmn.materialchips.ChipView.setHasAvatarIcon(ChipView.java:219)
                                                                               at com.pchmn.materialchips.ChipView.inflateWithAttributes(ChipView.java:122)
                                                                               at com.pchmn.materialchips.ChipView.newInstance(ChipView.java:448)
                                                                               at com.pchmn.materialchips.ChipView.access$000(ChipView.java:29)
                                                                               at com.pchmn.materialchips.ChipView$Builder.build(ChipView.java:432)
                                                                               at com.pchmn.materialchips.ChipsInput.getChipView(ChipsInput.java:207)
                                                                               at com.pchmn.materialchips.adapter.ChipsAdapter.onCreateViewHolder(ChipsAdapter.java:78)
                                                                               at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                               at com.beloo.widget.chipslayoutmanager.ChipsLayoutManager.fillWithLayouter(ChipsLayoutManager.java:858)
                                                                               at com.beloo.widget.chipslayoutmanager.ChipsLayoutManager.fill(ChipsLayoutManager.java:821)
                                                                               at com.beloo.widget.chipslayoutmanager.ChipsLayoutManager.onLayoutChildren(ChipsLayoutManager.java:719)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                               at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                                               at android.view.View.measure(View.java:19957)
                                                                               at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1420)
                                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                               at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:482)
                                                                               at com.pchmn.materialchips.views.ScrollViewMaxHeight.onMeasure(ScrollViewMaxHeight.java:47)
                                                                               at android.view.View.measure(View.java:19957)
                                                                               at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1420)
                                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                               at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:482)
                                                                               at com.pchmn.materialchips.views.ScrollViewMaxHeight.onMeasure(ScrollViewMaxHeight.java:47)
                                                                               at android.view.View.measure(View.java:19957)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                               at android.support.design.widget.TextInputLayout.onMeasure(TextInputLayout.java:1056)
                                                                               at android.view.View.measure(View.java:19957)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                               at android.view.View.measure(View.java:19957)
                                                                               at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1311)
                                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                               at android.widget.ScrollView.onMeasure(ScrollView.java:345)
                                                                               at android.view.View.measure(View.java:19957)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                               at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                               at android.view.View.measure(View.java:19957)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
                                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)`

**Comment by pchmn** [comment]
Can you provide the code that provoque this bug ? I think that this is because the `ChipView` label is probably null.

**Comment by duke1712** [comment]
Actually I clicked on the list dropdown from the chipInput and when I
clicked on that I got this error. Label cannot be null because if that was
the case then the dropdown from chipInput shouldn't hv come right?

**Comment by pchmn** [comment]
You're right. I fixed the bug and pushed it in v1.0.3. 
Telle me if it works.

**Comment by duke1712** [comment]
Yes it's fixed but now the letter icon is not coming when creating chips programmatically. The place where the letter icon should come is blank.

**Comment by pchmn** [comment]
I can't reproduce the bug. You're sure the label is not null when trying to create the letter icon ?

**Comment by duke1712** [comment]
Yes the label is not null, because if the label would have been null then the text inside the chip shouldn't come right?

**Comment by duke1712** [comment]
I am attaching the screenshot it may help you.
I am adding this chip programatically using 
chip.addChip()
![screenshot_20170420-233353](https://cloud.githubusercontent.com/assets/19251399/25245504/3e209076-2622-11e7-869b-aa4a4efd0877.png)

**Comment by duke1712** [comment]
I noticed that when adding chips using java, there is a NonNull Annotation in avatarIcon. My icon uri is null but I need the letter icon. So the error might be in the function addChip which is not accepting null avatarUri

**Comment by pchmn** [comment]
Yeah ok I will investigate this. Maybe I would be able to fix this only tomorrow, I'm sorry.

Thanks for your return and I'll tell you when this will be fixed

**Comment by duke1712** [comment]
Ya no problem, I am also experimenting on your sample project and if I get something il post it here.

**Comment by duke1712** [comment]
Modify these lines in your sample project which will help you recreate the bug.

ChipExampleActivity.java

```
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_chip_examples);
        // butter knife
        ButterKnife.bind(this);
        LinearLayout linearLayout=(LinearLayout)findViewById(R.id.abc);

        ChipView chip=new ChipView(this);
        chip.setLabel("Pritesh");
        chip.setPadding(2,2,2,2);
        chip.setHasAvatarIcon(true);
        linearLayout.addView(chip);

        // chip 1
        mChip1.setOnChipClicked(view -> {
            Toast.makeText(ChipExamplesActivity.this, mChip1.getLabel() + ": clicked", Toast.LENGTH_SHORT).show();
        });

```

activity_chip_Example.xml

`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.pchmn.sample.materialchipsinput.MainActivity">

    <LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="16dp">

        
        <LinearLayout
            android:id="@+id/abc"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="horizontal">

        </LinearLayout>

        <LinearLayout
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <com.pchmn.materialchips.ChipView
                android:id="@+id/chip2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginRight="16dp"
                app:label="Chip 1"
                app:hasAvatarIcon="false"
                app:deletable="false"/>
`

Just compare whith your code and make the changes to see the bug.

**Comment by pchmn** [comment]
So I tested as you taught me, but it works, I don't have your bug. A screenshot : 

![image](https://cloud.githubusercontent.com/assets/12658241/25282180/0317661a-26b0-11e7-8ff0-85e2f950130c.png)

**Comment by duke1712** [comment]
did you add it throgh java file or xml?
Xml is working perfect there ks a problem when adding chips from java file

**Comment by pchmn** [comment]
I added the chip with java : 

```java
        ChipView chipView1 = new ChipView(this);
        chipView1.setLabel("Pritesh");
        chipView1.setPadding(2,2,2,2);
        chipView1 .setHasAvatarIcon(true);

        mLayout.addView(chipView1);
```

**Comment by duke1712** [comment]
Ok I am trying once.

**Comment by pchmn** [comment]
The problem is still there ?

**Comment by duke1712** [comment]
The problem was still there. I am trying to debug the code and find the problem and notifying you soon.

**Comment by duke1712** [comment]
Okay bro thanx the latest version has solved. Thanks alot
