### ISSUE TITLE
java.lang.IllegalStateException: The specified child already has a parent.

### ISSUE THREAD

**Issue by emilmarkose** [pchmn/MaterialChipsInput#46]
I got his exception when I navigated away from a fragment where com.pchmn.materialchips.ChipsInput is used.

```
 FATAL EXCEPTION: main
                                                               Process: app.contactplus, PID: 3201
                                                               java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                   at android.view.ViewGroup.addViewInner(ViewGroup.java:4310)
                                                                   at android.view.ViewGroup.addView(ViewGroup.java:4146)
                                                                   at android.view.ViewGroup.addView(ViewGroup.java:4118)
                                                                   at com.pchmn.materialchips.views.FilterableListView$1.onGlobalLayout(FilterableListView.java:94)
                                                                   at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1996)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by emilmarkose** [comment]
Hi,

I've fixed this issue, by adding the following in FilterableListView.java

```
                //If this child view is already added to the parent rootView, then remove it first
                ViewGroup parent = (ViewGroup) FilterableListView.this.getParent();
                if (parent != null) {
                    parent.removeView(FilterableListView.this);
                }                
```

I added this before this

```
               // add view
               rootView.addView(FilterableListView.this, layoutParams);
```
I think you got the problem.
But this issue is not always happening. Cannot reproduce always.

BR
Emil

**Comment by FajarKhan** [comment]
+1 for this!

**Comment by FajarKhan** [comment]
@emilmarkose How do you edit Library files?

**Comment by emilmarkose** [comment]
Hi @FajarKhan,
You can't edit library files. You have to download the entire library into your project. Then only you can modify the source code.

**Comment by gregghz** [comment]
I've had several users his this in a production app. Is there a known work around that doesn't involve modify the library source?

**Comment by Pallav1196** [comment]
i have added the fix in the library , but it is reproducing the same issue again and again
