### ISSUE TITLE
NullPointerException at FilterableListView.fadeIn()

### ISSUE THREAD

**Issue by VamsiSmart** [pchmn/MaterialChipsInput#54]
Getting this error when  ` chips_input.setFilterableList(contactChips);` is called after network call

`java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$MarginLayoutParams.topMargin' on a null object reference
                                                                             at com.pchmn.materialchips.views.FilterableListView.fadeIn(FilterableListView.java:135)
                                                                             at com.pchmn.materialchips.views.FilterableListView$2.onFilterComplete(FilterableListView.java:113)
                                                                             at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:285)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

**Comment by alexnivanov** [comment]
Same for me:

`java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$MarginLayoutParams.topMargin' on a null object reference
                                                                 at com.pchmn.materialchips.views.FilterableListView.fadeIn(FilterableListView.java:135)
                                                                 at com.pchmn.materialchips.views.FilterableListView$2.onFilterComplete(FilterableListView.java:113)
                                                                 at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:285)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`

**Comment by gokrish6670** [comment]
when it will be resolved

java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$MarginLayoutParams.topMargin' on a null object reference at com.pchmn.materialchips.views.FilterableListView.fadeIn(FilterableListView.java:135)                                                                at com.pchmn.materialchips.views.FilterableListView$2.onFilterComplete(FilterableListView.java:113)                                                                   at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:285)                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:148)                                                                   at android.app.ActivityThread.main(ActivityThread.java:5438)  at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)a t com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by ChrisLMills** [comment]
And another....

FATAL EXCEPTION: main
                                                                   Process: website.picl.picl, PID: 19213
                                                                   java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$MarginLayoutParams.topMargin' on a null object reference
                                                                       at com.pchmn.materialchips.views.FilterableListView.fadeIn(FilterableListView.java:135)
                                                                       at com.pchmn.materialchips.views.FilterableListView$2.onFilterComplete(FilterableListView.java:113)
                                                                       at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:285)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:7409)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ChrisLMills** [comment]
I may have found a fix. I say 'may' because the issue was intermittent, but I haven't seen it occur since the change. You just need to wrap the following chunk of code at line 135 in FilterableListView.java in an 'if not null', thus preventing it from firing off until the view has loaded:

if (layoutParams != null) {
        layoutParams.topMargin = coord[1] + mChipsInput.getHeight();
        // height of the keyboard
        layoutParams.bottomMargin = rootView.getHeight() - r.bottom;
        setLayoutParams(layoutParams);

        AlphaAnimation anim = new AlphaAnimation(0.0f, 1.0f);
        anim.setDuration(200);
        startAnimation(anim);
        setVisibility(VISIBLE);
        }

I've added this change at ChrisLMills/MaterialChipsInput.

**Comment by Bestak** [comment]
Hi there, I have experienced this problem as well.
I tried the solution from @ChrisLMills, however this only stopped the app from crashing, not solving the main problem.
I looked into the code and noticed that there was this listener in FliterableListView:

```
mChipsInput.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {

            @Override
            public void onGlobalLayout() {
                  ...
            }
}
```
Everytime the dropdown failed to show, this listener wouldn't get called.

In my case I was downloading data from the internet and afterwards propagating them into the filterable list.
So I added this to the result of my http request:

```
...

// pass the Chip list
toChipsInput.setFilterableList(contactList);

toChipsInput.requestLayout(); //this is the new line I have added
```

This line makes sure, that the listener gets called and the LayoutParams get initilized.

Hope this helps.

**Comment by Yuvix25** [comment]
@Bestak That's it - works perfectly!
