### ISSUE TITLE
Null pointer exception when try to set chips on text changed

### ISSUE THREAD

**Issue by munirchauhan** [pchmn/MaterialChipsInput#69]
Process: com.pchmn.sample.materialchipsinput, PID: 23129
                                                                                     java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$MarginLayoutParams.topMargin' on a null object reference
                                                                                         at com.pchmn.materialchips.views.FilterableListView.fadeIn(FilterableListView.java:135)
                                                                                         at com.pchmn.materialchips.views.FilterableListView$2.onFilterComplete(FilterableListView.java:113)
                                                                                         at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:285)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by juandavidGF** [comment]
Any news on this bug?

**Comment by dmachacon** [comment]
I encountered this when I haven't set Filterable List then I type on edit text. So what I did was set a default list for the Filterable List and refresh the list whenever the user types on the edittext.
